from datetime import date, timedelta

from src.database.connection import SessionLocal
from src.database.crud import create_donor


session = SessionLocal()

donors = [
    {
        "name": "Ahmed Ali",
        "age": 25,
        "gender": "Male",
        "blood_type": "O+",
        "phone": "01000000001",
        "location": "Mansoura",
        "latitude": 31.0409,
        "longitude": 31.3785,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=100),
    },
    {
        "name": "Mohamed Hassan",
        "age": 30,
        "gender": "Male",
        "blood_type": "A+",
        "phone": "01000000002",
        "location": "Mansoura",
        "latitude": 31.0500,
        "longitude": 31.3900,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=80),
    },
    {
        "name": "Omar Samir",
        "age": 22,
        "gender": "Male",
        "blood_type": "B+",
        "phone": "01000000003",
        "location": "Mansoura",
        "latitude": 31.0600,
        "longitude": 31.4000,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=120),
    },
    {
        "name": "Youssef Ahmed",
        "age": 28,
        "gender": "Male",
        "blood_type": "A-",
        "phone": "01000000004",
        "location": "Talkha",
        "latitude": 31.0530,
        "longitude": 31.3800,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=90),
    },
    {
        "name": "Mariam Ali",
        "age": 24,
        "gender": "Female",
        "blood_type": "O-",
        "phone": "01000000005",
        "location": "Talkha",
        "latitude": 31.0500,
        "longitude": 31.3750,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=150),
    },
    {
        "name": "Sara Mohamed",
        "age": 27,
        "gender": "Female",
        "blood_type": "AB+",
        "phone": "01000000006",
        "location": "Mansoura",
        "latitude": 31.0450,
        "longitude": 31.3850,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=70),
    },
    {
        "name": "Nour Hassan",
        "age": 29,
        "gender": "Female",
        "blood_type": "B-",
        "phone": "01000000007",
        "location": "Mit Ghamr",
        "latitude": 30.7167,
        "longitude": 31.2667,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=110),
    },
    {
        "name": "Khaled Mahmoud",
        "age": 32,
        "gender": "Male",
        "blood_type": "O+",
        "phone": "01000000008",
        "location": "Zagazig",
        "latitude": 30.5877,
        "longitude": 31.5020,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=95),
    },
    {
        "name": "Menna Ibrahim",
        "age": 23,
        "gender": "Female",
        "blood_type": "A+",
        "phone": "01000000009",
        "location": "Mahalla",
        "latitude": 30.9700,
        "longitude": 31.1669,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=130),
    },
    {
        "name": "Mahmoud Adel",
        "age": 35,
        "gender": "Male",
        "blood_type": "AB-",
        "phone": "01000000010",
        "location": "Mansoura",
        "latitude": 31.0550,
        "longitude": 31.3850,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=100),
    },
    {
        "name": "Hana Ahmed",
        "age": 26,
        "gender": "Female",
        "blood_type": "O+",
        "phone": "01000000011",
        "location": "Talkha",
        "latitude": 31.0570,
        "longitude": 31.3700,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=85),
    },
    {
        "name": "Mostafa Said",
        "age": 31,
        "gender": "Male",
        "blood_type": "B+",
        "phone": "01000000012",
        "location": "Mansoura",
        "latitude": 31.0480,
        "longitude": 31.3950,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=75),
    },
    {
        "name": "Aya Mohamed",
        "age": 21,
        "gender": "Female",
        "blood_type": "A-",
        "phone": "01000000013",
        "location": "Zagazig",
        "latitude": 30.5900,
        "longitude": 31.5050,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=140),
    },
    {
        "name": "Karim Hassan",
        "age": 34,
        "gender": "Male",
        "blood_type": "O-",
        "phone": "01000000014",
        "location": "Mahalla",
        "latitude": 30.9750,
        "longitude": 31.1700,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=100),
    },
    {
        "name": "Salma Ali",
        "age": 26,
        "gender": "Female",
        "blood_type": "AB+",
        "phone": "01000000015",
        "location": "Mansoura",
        "latitude": 31.0420,
        "longitude": 31.3800,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=90),
    },
    {
        "name": "Amr Youssef",
        "age": 29,
        "gender": "Male",
        "blood_type": "B-",
        "phone": "01000000016",
        "location": "Mit Ghamr",
        "latitude": 30.7200,
        "longitude": 31.2700,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=125),
    },
    {
        "name": "Reem Mahmoud",
        "age": 24,
        "gender": "Female",
        "blood_type": "A+",
        "phone": "01000000017",
        "location": "Talkha",
        "latitude": 31.0540,
        "longitude": 31.3780,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=80),
    },
    {
        "name": "Tarek Ahmed",
        "age": 36,
        "gender": "Male",
        "blood_type": "O+",
        "phone": "01000000018",
        "location": "Zagazig",
        "latitude": 30.5850,
        "longitude": 31.5000,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=115),
    },
    {
        "name": "Laila Hassan",
        "age": 28,
        "gender": "Female",
        "blood_type": "AB-",
        "phone": "01000000019",
        "location": "Mahalla",
        "latitude": 30.9680,
        "longitude": 31.1650,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=105),
    },
    {
        "name": "Islam Mahmoud",
        "age": 33,
        "gender": "Male",
        "blood_type": "B+",
        "phone": "01000000020",
        "location": "Mansoura",
        "latitude": 31.0520,
        "longitude": 31.3920,
        "is_available": True,
        "last_donation_date": date.today() - timedelta(days=100),
    },
]


try:
    for donor in donors:
        create_donor(session, **donor)

    print(f"{len(donors)} donors inserted successfully.")

finally:
    session.close()